/**
 * Generates supabase/seed.sql from the data currently hard-coded in index.html.
 * Run once to migrate the existing 20 services + 3 categories into the database.
 *
 *   node scripts/build-seed.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const html = readFileSync(join(root, 'index.html'), 'utf8');
const manifest = JSON.parse(
  readFileSync(join(root, 'generated/service-media-manifest.json'), 'utf8'),
);

const SITE_ORIGIN = 'https://wavesign.art/';

/** Pull `const NAME = [ ... ];` / `= { ... };` literal out of the HTML and evaluate it. */
function extractLiteral(name) {
  let start = html.indexOf(`const ${name} =`);
  if (start === -1) start = html.indexOf(`let ${name} =`);
  if (start === -1) throw new Error(`literal ${name} not found`);
  let i = html.indexOf('=', start) + 1;
  while (' \n\r\t'.includes(html[i])) i++;
  const opener = html[i];
  const closer = opener === '[' ? ']' : '}';
  let depth = 0;
  let end = -1;
  let inStr = null;
  for (let j = i; j < html.length; j++) {
    const ch = html[j];
    if (inStr) {
      if (ch === '\\') { j++; continue; }
      if (ch === inStr) inStr = null;
      continue;
    }
    if (ch === '"' || ch === "'" || ch === '`') { inStr = ch; continue; }
    if (ch === opener) depth++;
    else if (ch === closer) {
      depth--;
      if (depth === 0) { end = j; break; }
    }
  }
  if (end === -1) throw new Error(`could not balance literal ${name}`);
  const src = html.slice(i, end + 1);
  // eslint-disable-next-line no-new-func
  return Function(`"use strict"; return (${src});`)();
}

const SERVICE_CATEGORIES = extractLiteral('SERVICE_CATEGORIES');
const SERVICES_CATALOG = extractLiteral('SERVICES_CATALOG');
const SERVICE_DETAIL_DESCRIPTIONS = extractLiteral('SERVICE_DETAIL_DESCRIPTIONS');

const LANGS = ['ru', 'uk', 'en'];

const sqlStr = (v) => (v == null ? 'null' : `'${String(v).replace(/'/g, "''")}'`);
const sqlJson = (obj) => `'${JSON.stringify(obj).replace(/'/g, "''")}'::jsonb`;
const sqlBool = (v) => (v ? 'true' : 'false');
const sqlNum = (v) => (v == null || Number.isNaN(v) ? 'null' : String(v));

function i18n(map, fallbackKey) {
  const out = {};
  for (const l of LANGS) out[l] = (map && map[l]) || (fallbackKey ? map?.[fallbackKey] : '') || '';
  return out;
}

function absUrl(src) {
  if (!src) return null;
  try {
    return new URL(src.replace(/^\.\//, ''), SITE_ORIGIN).href;
  } catch {
    return null;
  }
}

const lines = [];
lines.push('-- Generated by scripts/build-seed.mjs — initial migration of existing site content.');
lines.push('-- Safe to re-run: rows are matched by slug.');
lines.push('');

// categories -----------------------------------------------------------------
SERVICE_CATEGORIES.forEach((cat, idx) => {
  const name = i18n(cat.name);
  lines.push(
    `insert into public.categories (slug, name, is_published, sort_order) values ` +
      `(${sqlStr(cat.id)}, ${sqlJson(name)}, true, ${idx}) ` +
      `on conflict (slug) do update set name = excluded.name, sort_order = excluded.sort_order;`,
  );
});
lines.push('');

// services ------------------------------------------------------------------
SERVICES_CATALOG.forEach((svc, idx) => {
  const title = i18n(svc.name);
  const detail = i18n(SERVICE_DETAIL_DESCRIPTIONS[svc.id] || {});
  const shortDesc = detail;
  const description = Object.fromEntries(
    LANGS.map((l) => [l, detail[l] ? `<p>${detail[l]}</p>` : '']),
  );
  const priceAmount = svc.price?.from ?? null;
  const priceUnit = svc.price?.unit ?? null;
  const media = manifest[svc.id] || {};
  const mainImage = absUrl(media.cover?.src || media.items?.[0]?.src || null);

  lines.push(
    `insert into public.services (` +
      `slug, title, short_description, description, price_amount, price_currency, price_type, price_unit, ` +
      `main_image_url, is_published, sort_order, sub_group, category_id` +
      `) values (` +
      `${sqlStr(svc.id)}, ${sqlJson(title)}, ${sqlJson(shortDesc)}, ${sqlJson(description)}, ` +
      `${sqlNum(priceAmount)}, 'USD', 'from', ${sqlStr(priceUnit)}, ` +
      `${sqlStr(mainImage)}, true, ${idx}, ${svc.group ?? 0}, ` +
      `(select id from public.categories where slug = ${sqlStr(svc.categoryId)})` +
      `) on conflict (slug) do update set ` +
      `title = excluded.title, short_description = excluded.short_description, ` +
      `description = excluded.description, price_amount = excluded.price_amount, ` +
      `price_unit = excluded.price_unit, main_image_url = excluded.main_image_url, ` +
      `sort_order = excluded.sort_order, sub_group = excluded.sub_group, ` +
      `category_id = excluded.category_id;`,
  );

  const items = Array.isArray(media.items) ? media.items : [];
  const gallery = items
    .map((it) => absUrl(it.src))
    .filter((u, i, arr) => u && arr.indexOf(u) === i);
  if (gallery.length) {
    lines.push(
      `delete from public.service_images where service_id = ` +
        `(select id from public.services where slug = ${sqlStr(svc.id)});`,
    );
    gallery.forEach((url, gi) => {
      lines.push(
        `insert into public.service_images (service_id, image_url, sort_order) values (` +
          `(select id from public.services where slug = ${sqlStr(svc.id)}), ${sqlStr(url)}, ${gi});`,
      );
    });
  }
});
lines.push('');

writeFileSync(join(root, 'supabase/seed.sql'), lines.join('\n') + '\n', 'utf8');
console.log(
  `seed.sql written — ${SERVICE_CATEGORIES.length} categories, ${SERVICES_CATALOG.length} services`,
);
