/**
 * Re-encodes every service image referenced by the media manifest as a
 * web-sized WebP under /assets/services/, rewrites the manifest to point at
 * them, and emits supabase/repoint-images.sql to move the live database
 * (services.main_image_url + service_images.image_url) onto the new files.
 *
 * Originals in "дизайн и анимация/" are left untouched. Videos pass through.
 *
 *   npm run optimize:images
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, extname } from 'node:path';
import { fileURLToPath } from 'node:url';
import sharp from 'sharp';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const ORIGIN = 'https://wavesign.art';
const OUT_DIR = 'assets/services';
const MAX_W = 1400;
const GIF_MAX_W = 720;

const IMG_EXT = new Set(['jpg', 'jpeg', 'png', 'webp']);

const manifest = JSON.parse(readFileSync(join(root, 'generated/service-media-manifest.json'), 'utf8'));

const decode = (src) => decodeURIComponent(String(src).replace(/^\.\//, ''));
const absUrl = (relOrDecoded) => new URL(relOrDecoded.replace(/^\.\//, ''), ORIGIN + '/').href;

const remap = new Map(); // oldAbsoluteUrl -> newAbsoluteUrl
let done = 0;
let skippedMissing = 0;
let passthroughVideo = 0;

async function processItem(item) {
  const type = item.type;
  const ext = (item.extension || extname(item.src).slice(1) || '').toLowerCase();
  if (type === 'video' || (ext !== 'gif' && !IMG_EXT.has(ext))) {
    passthroughVideo += type === 'video' ? 1 : 0;
    return item;
  }
  if (decode(item.src).startsWith(OUT_DIR + '/')) return item; // already optimized

  const relSrc = decode(item.src); // e.g. "дизайн и анимация/лого/cover.png"
  const abs = join(root, relSrc);
  if (!existsSync(abs)) {
    skippedMissing++;
    console.warn('  missing:', relSrc);
    return item;
  }

  const outRel = `${OUT_DIR}/${relSrc.replace(/^дизайн и анимация\//, '').replace(/\.[^.]+$/, '')}.webp`;
  const outAbs = join(root, outRel);
  mkdirSync(dirname(outAbs), { recursive: true });

  let pipeline;
  let width = item.width;
  let height = item.height;
  if (ext === 'gif') {
    pipeline = sharp(abs, { animated: true }).resize({ width: GIF_MAX_W, withoutEnlargement: true });
    const meta = await sharp(abs).metadata();
    if (meta.width && meta.width > GIF_MAX_W) {
      const scale = GIF_MAX_W / meta.width;
      width = GIF_MAX_W;
      height = Math.round((meta.height || meta.pageHeight || 0) * scale);
    }
    await pipeline.webp({ quality: 55, effort: 4 }).toFile(outAbs);
  } else {
    pipeline = sharp(abs)
      .rotate()
      .resize({ width: MAX_W, withoutEnlargement: true })
      .webp({ quality: 78, effort: 5 });
    const info = await pipeline.toFile(outAbs);
    width = info.width;
    height = info.height;
  }

  const beforeKb = Math.round(readFileSync(abs).length / 1024);
  const afterKb = Math.round(readFileSync(outAbs).length / 1024);
  done++;
  console.log(`  ${relSrc.split('/').slice(-2).join('/')}  ${beforeKb}KB -> ${afterKb}KB`);

  remap.set(absUrl(item.src), absUrl('./' + outRel));

  return {
    ...item,
    src: './' + outRel.split('/').map(encodeURIComponent).join('/'),
    extension: 'webp',
    type: 'image',
    ...(width ? { width } : {}),
    ...(height ? { height } : {}),
  };
}

for (const [slug, data] of Object.entries(manifest)) {
  if (!data || !Array.isArray(data.items) || data.items.length === 0) continue;
  console.log(slug);
  data.items = await Promise.all(data.items.map(processItem));
  if (data.cover) {
    const optimized = data.items.find((it) => absUrl(it.src) === (remap.get(absUrl(data.cover.src)) ?? '___')) ||
      data.items.find((it) => decode(it.src).endsWith(decode(data.cover.src).replace(/\.[^.]+$/, '') + '.webp'));
    data.cover = optimized || data.items.find((it) => it.isCover) || data.items[0];
  }
}

/* write manifest (.json + .js) */
const jsonOut = JSON.stringify(manifest, null, 2);
writeFileSync(join(root, 'generated/service-media-manifest.json'), jsonOut + '\n', 'utf8');
writeFileSync(
  join(root, 'generated/service-media-manifest.js'),
  `/* Generated by scripts/optimize-images.mjs. Do not edit by hand. */\nwindow.SERVICE_MEDIA_MANIFEST = ${jsonOut};\n`,
  'utf8',
);

/* SQL to move the live DB onto the optimized files */
if (remap.size) {
  const lines = [
    '-- Point the database at the optimized /assets/services/*.webp images.',
    '-- Generated by scripts/optimize-images.mjs — run once in the Supabase SQL Editor',
    '-- AFTER these files are deployed (git push).',
    '',
  ];
  for (const [oldUrl, newUrl] of remap) {
    const o = oldUrl.replace(/'/g, "''");
    const n = newUrl.replace(/'/g, "''");
    lines.push(`update public.services set main_image_url = '${n}' where main_image_url = '${o}';`);
    lines.push(`update public.service_images set image_url = '${n}' where image_url = '${o}';`);
  }
  lines.push('');
  writeFileSync(join(root, 'supabase/repoint-images.sql'), lines.join('\n'), 'utf8');
}

console.log(
  `\noptimized ${done} images/gifs -> ${OUT_DIR}/  (videos passed through: ${passthroughVideo}, missing: ${skippedMissing})`,
);
console.log(remap.size ? 'wrote supabase/repoint-images.sql' : '');
